-- =============================================================================
-- portfoliq pack: fact_ai_analysis
-- Source : star_public.fact_ai_analysis
-- Grain  : (asset_sk, analysis_type_id, generated_date) — latest analysis per day
-- Toggle : portfoliq_enable_star
--
-- Content generated by Claude Haiku 4.5 (85%) / Sonnet 4.6 (15%).
-- Internal metrics excluded: cost_usd_micros, cache_hit (never exposed).
-- AMF guard applied at ingestion: investment_verdict / fair_value FORBIDDEN.
--
-- Legal  : ai_generated=true required on all endpoints exposing this model.
--          Not financial advice. Methodology disclosed.
-- Licence: ELv2 — see NOTICE.md
-- =============================================================================

{{ assert_star_enabled() }}

select
    ai_analysis_sk,
    asset_sk,
    analysis_type_id,
    date_sk,
    generated_date,
    model_id,
    prompt_version,
    content_json,
    methodology_version

from {{ source('portfoliq', 'fact_ai_analysis') }}

{% if not var('portfoliq_enable_star', true) %}
where false
{% endif %}
